name: Azure Deployment Pipeline

trigger:
  branches:
    include:
      - main

jobs:
  - job: Build_and_Deploy
    displayName: 'Build and Deploy'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          version: '3.x'

      # Hier kommen weitere Schritte zum Build deiner Anwendung

      - script: |
          echo 'Building the application...'
          # Befehl zum Builden der Anwendung hier einf端gen
        displayName: 'Build the Application'

      - script: |
          echo 'Running tests...'
          # Befehl zum Ausf端hren von Tests hier einf端gen
        displayName: 'Run Tests'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '<Pfad zum Build-Artefakt>'
          ArtifactName: 'drop'

  - job: Deploy_to_Azure
    displayName: 'Deploy to Azure'
    dependsOn: Build_and_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          buildType: 'specific'
          project: '<Projektname>'
          definition: '<Build-Definition-Name>'
          buildVersionToDownload: 'latest'

      - task: AzureCLI@2
        displayName: 'Azure Login'
        inputs:
          azureSubscription: '<Name der Azure-Serviceverbindung>'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az login --service-principal -u <Service Principal ID> -p <Service Principal Key> --tenant <Tenant ID>
        env:
          AZURE_SERVICE_PRINCIPAL_PASSWORD: $(AZURE_SERVICE_PRINCIPAL_PASSWORD)

      - script: |
          echo 'Deploying to Azure...'
          # Befehl zum Deployment in Azure hier einf端gen
        displayName: 'Deploy to Azure