name: Validate and Deploy Azure Resources

on:
  push:
    branches:
      - master

jobs:
  validate_and_deploy:
    runs-on: windows-latest

    # Download repository
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    # Display service principal details
    - name: Display Service Principal Details
      run: |
        echo "Client ID: $CLIENT_ID"
        echo "Client Secret: $CLIENT_SECRET"
        echo "Tenant ID: $TENANT_ID"
      env:
        CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
    # Uninstall AzureRm module
    - name: Uninstall AzureRm module
      run: Uninstall-Module -Name AzureRm -Force -ErrorAction SilentlyContinue

    # Install packages that are needed for the deployment
    - name: Install Azure PowerShell module
      run: Install-Module -Name Az -Force -AllowClobber

    # Connecting to Azure
    - name: Login to Azure
      run: |
        $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
        }
        $credential = New-Object -TypeName PSCredential -ArgumentList $servicePrincipal.clientId, $(ConvertTo-SecureString -String $servicePrincipal.clientSecret -AsPlainText -Force)

        Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $servicePrincipal.tenantId

    # Validate Bicep files
    - name: Validate Bicep files
      run: |
        az bicep build -f *.bicep --out

    # Execute PowerShell script
    - name: Execute PowerShell Script
      shell: pwsh
      run: |
        az deployment group create --resource-group rg-david-schaefer --template-file ./UserStory3/userStoryTwo.bicep --parameters ./UserStory3/parameters.prod.json --mode complete
