name: Deploy to Azure

on: [push]
jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Azure PowerShell module
      run: Install-Module -Name Az -Force -AllowClobber
    
    - name: Login to Azure
      run: |
        $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
        }
        $credential = New-Object -TypeName PSCredential -ArgumentList $servicePrincipal.clientId, $(ConvertTo-SecureString -String $servicePrincipal.clientSecret -AsPlainText -Force)

        Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $servicePrincipal.tenantId
    
    - name: Deploy to Azure
      run: |
        az group deployment create --resource-group rg-david-schaefer --template-file C:\Users\David.Schaefer\DevOps\UserStory3\userStoryTwo.bicep --parameters C:\Users\David.Schaefer\DevOps\UserStory3\parameters.prod.json
