name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Check if Userstory3.bicep exists
        id: check_userstory3
        run: |
          if [ -f ./UserStory3/userStoryTwo.bicep ]; then
            echo "exists"
          else
            echo "not_exists"
          fi
        shell: bash

      - name: Deploy Bicep file 3
        run: |
          if [[ $(echo "${{ steps.check_userstory3.outputs }}" | tr -d '\r\n') == "exists" ]]; then
            az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./UserStory3/userStoryTwo.bicep --parameters location=westeurope --mode complete
          else
            az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./UserStory3/userStoryTwo.bicep --parameters location=westeurope
          fi
